version: '3.9'

services:

  mockavior:
    image: unisoft123/mockavior:latest
    container_name: mockavior
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MOCKAVIOR_CONTRACT_PATH: /app/config/mockapi.yml
    volumes:
      - ./config:/app/config:ro
    networks:
      - mockavior

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - mockavior

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - mockavior

networks:
  mockavior:
    driver: bridge