version: 1

kafka:
  scenarios:
    - id: user-events
      repeat: 1000000
      messages:
        - topic: user.created
          key: "user-1"
          value:
            id: 1
            name: Alice
          repeat: 1

        - topic: user.updated
          key: "user-1"
          value:
            id: 1
            name: Alice Smith
          repeat: 2

endpoints: []
