version: 1

kafka:
  scenarios:
    - id: user-events
      repeat: 4
      messages:
        - topic: user.created
          key: "user-1"
          value:
            id: 1
            name: Alice
          repeat: 1
          delay:
            fixed: 2000
            random:
              min: 1000
              max: 5000

#        - topic: user.updated
#          key: "user-1"
#          value:
#            id: 1
#            name: Alice Smith
#          repeat: 2

endpoints: []
