settings:
  mode: PASSTHROUGH
  proxy:
    baseUrl: https://httpbin.org

endpoints:
  - id: health-check
    priority: 10
    request:
      protocol: http
      method: GET
      path: /health
    response:
      type: mock
      status: 200
      body: "OK!!!"


kafka:
  scenarios:
    - id: user-events
      repeat: 5
      messages:
        - topic: user.created
          key: "user-1"
          value:
            id: 1
            name: Alice
          repeat: 1

        - topic: user.updated
          key: "user-1"
          value:
            id: 1
            name: Alice Smith
          repeat: 2